"""empty message

Revision ID: f80213abe04e
Revises: bae6bf4eac94
Create Date: 2024-04-22 01:41:21.857771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80213abe04e'
down_revision = 'bae6bf4eac94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_first', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name_last', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name_last')
        batch_op.drop_column('name_first')

    # ### end Alembic commands ###
